# Generated by Django 5.0.5 on 2024-05-14 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_productdb_price_alter_categorydb_categoryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='CY_Name',
            new_name='CName',
        ),
    ]
