# Generated by Django 5.0.5 on 2024-05-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_rename_cy_name_productdb_cname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='CName',
            new_name='Category',
        ),
    ]
