# Generated by Django 5.0.5 on 2024-06-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_registerdb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerdb',
            name='Country',
        ),
    ]
