# Generated by Django 5.0.5 on 2024-06-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0003_remove_registerdb_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.IntegerField(blank=True, null=True)),
                ('Carname', models.CharField(blank=True, max_length=100, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
