# Generated by Django 5.0.5 on 2024-06-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_wishlistdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistdb',
            name='Price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
