# Generated by Django 5.0.5 on 2024-06-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0005_alter_wishlistdb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistdb',
            name='Username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
