# Generated by Django 5.0.5 on 2024-06-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_orderdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdb',
            name='Price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
