# Generated by Django 5.0.5 on 2024-06-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_orderdb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdb',
            name='Price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
